name: 'Terraform Deploy'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Action to perform (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
  pull_request:

permissions:
  contents: read
  id-token: write # Required for requesting the JWT

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_vpc_east_name: ${{ vars.VPC_EAST_NAME }}
      TF_VAR_gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      
    defaults:
      run:
        working-directory: ./gcp-vnets
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        policy_type: 'gcp'
        only_warn: false # Set to false to block deployment if violations are found
        sarif_upload: true
        iac_dir: ./gcp-vnets

     # Authenticate to GCP using Workload Identity Federation
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ vars.WORKLOAD_INDENTITY_PROVIDER }}
        service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
   
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Action
      # Logic to choose between Apply and Destroy
      run: |
        if [ "${{ github.event.inputs.terraform_action }}" == "destroy" ]; then
          terraform destroy -auto-approve
        else
          terraform apply -auto-approve
        fi
